/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const default_sidebars: SidebarsConfig = {
  left_sidebar: [
      {type: 'autogenerated', dirName: '.'}
  ],
};

export default default_sidebars;
