/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
      {type: 'doc', id: 'welcome'},
      {type: 'doc', id: 'whats_new'},
      {type: 'category', label: 'API', link: {type: 'generated-index', description: 'API documentation for Fiber.'}, items: [{type: 'autogenerated', dirName: 'api'}]},
      {type: 'category', label: 'Guide', link: {type: 'generated-index', description: 'Guides for Fiber.'}, items: [{type: 'autogenerated', dirName: 'guide'}]},
      {type: 'category', label: 'Extra', link: {type: 'generated-index', description: 'Extra contents for Fiber.'}, items: [{type: 'autogenerated', dirName: 'extra'}]},
      // replace this without partials folder when the exclude feature is there fo rthe autogenerated feature
      // {type: 'autogenerated', dirName: '.'}
  ],
};

module.exports = sidebars;
